# Cloud Scheduler ジョブ設定
name: projects/PROJECT_ID/locations/asia-northeast1/jobs/receipt-processor-job
description: "領収書自動処理システムの定期実行"
schedule: "0 */6 * * *"  # 6時間毎に実行
timeZone: "Asia/Tokyo"

httpTarget:
  uri: "https://receipt-processor-PROJECT_ID.a.run.app/"
  httpMethod: POST
  headers:
    Content-Type: "application/json"
  body: eyJydW4iOiJ0cnVlIn0=  # {"run":"true"} のBase64エンコード
  oidcToken:
    serviceAccountEmail: "receipt-processor@PROJECT_ID.iam.gserviceaccount.com"

retryConfig:
  retryCount: 3
  maxRetryDuration: "300s"
  minBackoffDuration: "60s"
  maxBackoffDuration: "180s"
