apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: receipt-processor
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/max-instance-count: "10"
        run.googleapis.com/min-instance-count: "0"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 3600
      containers:
      - image: gcr.io/PROJECT_ID/receipt-processor:latest
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 2Gi
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/secrets/google-credentials"
        - name: NOTION_TOKEN
          valueFrom:
            secretKeyRef:
              name: notion-secrets
              key: token
        - name: GOOGLE_DRIVE_MONITOR_FOLDER
          value: "receipts"
        - name: NOTION_DATABASE_ID
          valueFrom:
            secretKeyRef:
              name: notion-secrets
              key: database-id
        - name: LOG_LEVEL
          value: "INFO"
        volumeMounts:
        - name: google-credentials
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials

