name: HETEML Monitor

on:
  schedule:
    # 6時間ごとに実行（月124時間 = 7,440分）
    - cron: '0 */6 * * *'
  workflow_dispatch:  # 手動実行も可能

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd HETEMLMonitor
        pip install -r requirements.txt
        
    - name: Create config file and directories
      run: |
        cd HETEMLMonitor
        cp config.example.py config.py
        mkdir -p logs
      env:
        HETEML_PASSWORD: ${{ secrets.HETEML_PASSWORD }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        
    - name: Debug environment
      run: |
        cd HETEMLMonitor
        echo "Current directory: $(pwd)"
        echo "Files in directory:"
        ls -la
        echo "Config file exists:"
        ls -la config.py || echo "Config file not found"
        echo "Python version:"
        python --version
        echo "Installed packages:"
        pip list | grep -E "(paramiko|requests|python-dotenv)"
        
    - name: Run basic test first
      run: |
        cd HETEMLMonitor
        echo "=== 基本テスト開始 ==="
        python test_basic.py
        echo "=== 基本テスト終了 ==="
        
    - name: Run minimal test
      run: |
        cd HETEMLMonitor
        echo "=== 最小限テスト開始 ==="
        python test_minimal.py
        echo "=== 最小限テスト終了 ==="
      env:
        HETEML_PASSWORD: ${{ secrets.HETEML_PASSWORD }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        
    - name: Run HETEML Monitor
      run: |
        cd HETEMLMonitor
        echo "=== スクリプト実行開始 ==="
        python -u heteml_monitor_github_action.py 2>&1
        echo "=== スクリプト実行終了 ==="
      env:
        HETEML_PASSWORD: ${{ secrets.HETEML_PASSWORD }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        
    - name: Upload logs as artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: heteml-monitor-logs
        path: HETEMLMonitor/logs/
        retention-days: 7
