name: MovableType Monthly Rebuild

on:
  schedule:
    # 毎月1日の0:05 日本時間 (UTC 15:05 前日) に実行
    - cron: '5 15 1 * *'
  workflow_dispatch:  # 手動実行も可能

jobs:
  rebuild:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 30分でタイムアウト
    env:
      TZ: Asia/Tokyo  # 日本時間を明示
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd MovableTypeRebuilder
        pip install -r requirements.txt
        
    - name: Create logs directory and setup .env
      run: |
        cd MovableTypeRebuilder
        mkdir -p logs
        # 環境変数から.envファイルを作成
        cat > .env << EOF
        # MovableType設定
        MT_SITE_URL=https://nbspress.com/mt/mt.cgi
        MT_USERNAME=admin
        MT_PASSWORD=Z9MSNPSknzmr
        MT_BLOG_ID=45
        MT_SITE_NAME=公演カレンダー
        
        # メール通知設定
        EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
        FROM_EMAIL=${{ secrets.FROM_EMAIL }}
        TO_EMAIL=${{ secrets.TO_EMAIL }}
        
        # 実行設定
        REBUILD_INTERVAL_MINUTES=5
        MAX_RETRY_COUNT=3
        LOG_LEVEL=INFO
        EOF
        
        # 環境変数の確認
        echo "=== 環境変数確認 ==="
        echo "MT_SITE_URL: https://nbspress.com/mt/mt.cgi"
        echo "MT_USERNAME: admin"
        echo "MT_BLOG_ID: 45"
        echo "MT_SITE_NAME: 公演カレンダー"
        
    - name: Run MovableType rebuild
      run: |
        cd MovableTypeRebuilder
        echo "=== MovableType再構築開始 ==="
        echo "実行時刻: $(date)"
        echo "対象サイト: 公演カレンダー (blog_id: 45)"
        echo "サイトURL: https://nbspress.com/mt/mt.cgi"
        echo "ユーザー名: admin"
        echo "パスワード: ***"
        
        # 環境変数を設定
        export MT_SITE_URL=https://nbspress.com/mt/mt.cgi
        export MT_USERNAME=admin
        export MT_PASSWORD=Z9MSNPSknzmr
        export MT_BLOG_ID=45
        export MT_SITE_NAME=公演カレンダー
        export EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}
        export EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
        export FROM_EMAIL=${{ secrets.FROM_EMAIL }}
        export TO_EMAIL=${{ secrets.TO_EMAIL }}
        export REBUILD_INTERVAL_MINUTES=5
        export MAX_RETRY_COUNT=3
        export LOG_LEVEL=INFO
        
        # 環境変数の確認
        echo "=== 環境変数確認（export後） ==="
        echo "MT_SITE_URL=$MT_SITE_URL"
        echo "MT_USERNAME=$MT_USERNAME"
        echo "MT_BLOG_ID=$MT_BLOG_ID"
        echo "MT_SITE_NAME=$MT_SITE_NAME"
        
        # .envファイルの確認
        echo "=== .envファイルの確認 ==="
        cat .env
        
        # Pythonスクリプト実行（PYTHONPATH設定）
        cd /home/runner/work/TakuhitoVault/TakuhitoVault/MovableTypeRebuilder
        PYTHONPATH=/home/runner/work/TakuhitoVault/TakuhitoVault/MovableTypeRebuilder:$PYTHONPATH python scripts/mt_rebuilder_github_action.py
        echo "=== MovableType再構築完了 ==="
        echo "完了時刻: $(date)"
        
    - name: Check logs
      if: always()
      run: |
        cd MovableTypeRebuilder
        echo "=== ログファイル確認 ==="
        ls -la logs/ || echo "ログディレクトリが存在しません"
        if [ -f logs/mt_rebuilder_$(date +%Y%m%d).log ]; then
          echo "=== 今日のログ内容 ==="
          cat logs/mt_rebuilder_$(date +%Y%m%d).log
        else
          echo "今日のログファイルが見つかりません"
        fi
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mt-rebuild-logs
        path: MovableTypeRebuilder/logs/
        retention-days: 30
